#!/bin/zsh
setopt no_unset
set -x
cd $0:h || exit $?
export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:/usr/lib/pkgconfig
if [[ -e .last-installed-rev ]]; then
	rev=$(<.last-installed-rev)
else
	rev=NONE || exit $?
fi
git pull --ff-only || exit $?
if [[ $rev != $(git rev-parse HEAD) ]]; then
	if [[ -e Makefile ]]; then
		make clean || exit $?
	fi
	./configure --prefix=$HOME/local|| exit $?
	make -j8 CFLAGS='-g -O0' || exit $?
	make install || exit $?
fi
